import { initializeApp, deleteApp } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, signOut, createUserWithEmailAndPassword } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, collection, getDocs, deleteDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyBqxNT9EJLIFFazHKgDuBesC6CJt6Y8kZY',authDomain:'prepositions-ct.firebaseapp.com',projectId:'prepositions-ct',storageBucket:'prepositions-ct.firebasestorage.app',messagingSenderId:'185533456216',appId:'1:185533456216:web:b975529378af9dfc2a4f2d',measurementId:'G-MSQK3VZE9F'};
const firebaseApp=initializeApp(firebaseConfig),auth=getAuth(firebaseApp),firestore=getFirestore(firebaseApp);
const $=s=>document.querySelector(s);let db,state,currentUser,currentRole,session;
const EMPTY={unlocked:1,completed:{},stars:0,streak:1,errors:[]};
const modules=['Повседневная жизнь','Учёба и развитие','Люди и общение','Мир вокруг нас','Здоровье и безопасность','Работа и общество','Сложные конструкции'];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const studentEmail=(name,code)=>`${name.toLowerCase().normalize('NFKD').replace(/[^a-zа-яё0-9]+/gi,'').split('').map(c=>c.charCodeAt(0).toString(36)).join('').slice(0,42)}.${code.toLowerCase()}@students.prepositions-ct.local`;
const code=()=>Array.from({length:6},()=> 'ABCDEFGHJKMNPQRSTUVWXYZ23456789'[Math.floor(Math.random()*30)]).join('');
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2100)}
function setTop(name='Гость',initials='?'){$('#profileBtn').innerHTML=`${esc(initials)} <span>${esc(name)}</span>`}
function authScreen(){setTop();$('#app').innerHTML=`<div class="view auth-wrap"><section class="auth-card"><div class="eyebrow">PREPOSITION QUEST CT</div><h1>Вход в тренажёр</h1><p class="lead">Продолжай обучение с любого устройства — прогресс сохранится автоматически.</p><div class="auth-tabs"><button class="auth-tab active" data-tab="student">Ученик</button><button class="auth-tab" data-tab="teacher">Преподаватель</button></div><form id="studentLogin" class="auth-form"><label>Имя ученика<input id="studentName" required autocomplete="username" placeholder="Например, Марта"></label><label>Личный код<input id="studentCode" required minlength="6" maxlength="12" autocomplete="current-password" placeholder="Например, K7M4PX"></label><button class="btn" type="submit">Войти</button></form><form id="teacherLogin" class="auth-form hidden"><label>Email<input id="teacherEmail" type="email" required autocomplete="username" placeholder="Ваш email"></label><label>Пароль<input id="teacherPassword" type="password" required autocomplete="current-password" placeholder="Пароль Firebase"></label><button class="btn" type="submit">Войти как преподаватель</button></form><p id="authError" class="auth-error"></p></section></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.auth-tab').forEach(x=>x.classList.toggle('active',x===b));$('#studentLogin').classList.toggle('hidden',b.dataset.tab!=='student');$('#teacherLogin').classList.toggle('hidden',b.dataset.tab!=='teacher');$('#authError').textContent=''});$('#studentLogin').onsubmit=loginStudent;$('#teacherLogin').onsubmit=loginTeacher}
async function loginStudent(e){e.preventDefault();const name=$('#studentName').value.trim(),access=$('#studentCode').value.trim().toUpperCase();try{await signInWithEmailAndPassword(auth,studentEmail(name,access),access)}catch{$('#authError').textContent='Неверное имя или личный код.'}}
async function loginTeacher(e){e.preventDefault();try{await signInWithEmailAndPassword(auth,$('#teacherEmail').value.trim(),$('#teacherPassword').value)}catch{$('#authError').textContent='Не удалось войти. Проверьте email и пароль.'}}
async function detectRole(u){const teacher=await getDoc(doc(firestore,'teachers',u.uid));if(teacher.exists())return['teacher',teacher.data()];const student=await getDoc(doc(firestore,'students',u.uid));if(student.exists())return['student',student.data()];return[null,null]}
async function save(){if(!currentUser||currentRole!=='student')return;await setDoc(doc(firestore,'students',currentUser.uid),{displayName:state.name,unlocked:state.unlocked,completed:state.completed,stars:state.stars,streak:state.streak,errors:state.errors,lastActiveAt:serverTimestamp()},{merge:true})}
async function logout(){await signOut(auth)}
function shuffle(a){return[...a].sort(()=>Math.random()-.5)}function cardItems(id){return db.expressions.filter(x=>x.cardId===id)}
function header(){return`<section class="hero"><div class="hero-main"><div class="eyebrow">Твой путь к высокому баллу</div><h1>Прокачай <span class="gradient-text">предлоги</span><br>до автоматизма</h1><p class="lead">35 тематических карточек, короткие тренировки и умное повторение ошибок.</p><div class="hero-actions"><button class="btn" data-start="${Math.min(state.unlocked,35)}">Продолжить →</button><button class="btn secondary" id="mistakes">Мои ошибки · ${state.errors.length}</button></div></div><aside class="hero-side"><div><div class="eyebrow" style="color:white">Общий прогресс</div><div class="level-ring"><strong>${Math.round(Object.keys(state.completed).length/35*100)}<span>%</span></strong></div></div><div class="stat-row"><div class="mini-stat"><strong>${Object.keys(state.completed).length}</strong><span>карточек</span></div><div class="mini-stat"><strong>${state.stars}</strong><span>звёзд</span></div><div class="mini-stat"><strong>${state.streak}</strong><span>дней подряд</span></div></div></aside></section>`}
function home(){let html=`<div class="view">${header()}<div class="section-head"><div><h2>Карта курса</h2><p>Проходи карточки последовательно и открывай новые модули</p></div></div>`;for(let m=0;m<7;m++){html+=`<section class="module"><h3 class="module-title"><span>${m+1}</span>${modules[m]}</h3><div class="card-grid">`;for(let j=1;j<=5;j++){const id=m*5+j,c=db.cards[id-1],locked=id>state.unlocked,done=state.completed[id];html+=`<button class="course-card ${locked?'locked':''} ${done?'completed':''}" data-card="${id}" ${locked?'disabled':''}><span class="status">${done?'✓':locked?'🔒':'→'}</span><span class="card-number">КАРТОЧКА ${String(id).padStart(2,'0')}</span><h3>${esc(c.title)}</h3><div class="card-meta"><span>${cardItems(id).length} выражений</span><span>${done?done+'%':'не начато'}</span></div></button>`}const ok=state.completed[(m+1)*5];html+=`<button class="course-card test-card ${ok?'':'locked'}" ${ok?'data-test="'+(m+1)+'"':'disabled'}><span class="status">${ok?'★':'🔒'}</span><span class="card-number">КОНТРОЛЬ ${m+1}</span><h3>Проверь знания модуля</h3><div class="card-meta"><span>30 заданий</span><span>проходной 80%</span></div></button></div></section>`}$('#app').innerHTML=html+'</div>';document.querySelectorAll('[data-card],[data-start]').forEach(b=>b.onclick=()=>openCard(+(b.dataset.card||b.dataset.start)));document.querySelectorAll('[data-test]').forEach(b=>b.onclick=()=>startTest(+b.dataset.test));$('#mistakes').onclick=()=>state.errors.length?startPractice(shuffle(db.expressions.filter(x=>state.errors.includes(x.id))).slice(0,20),true):toast('Ошибок пока нет — отлично!')}
function openCard(id){const items=cardItems(id),c=db.cards[id-1];$('#app').innerHTML=`<div class="view trainer"><button class="back" id="back">← К карте курса</button><section class="question-card"><div class="eyebrow">Карточка ${id} · ${items.length} выражений</div><h2>${esc(c.title)}</h2><p class="lead">Изучи выражения и выполни 20 случайных заданий. Проходной результат — 80%.</p><div class="hero-actions"><button class="btn" id="practice">Начать тренировку</button><button class="btn secondary" id="learn">Изучить выражения</button></div></section></div>`;$('#back').onclick=home;$('#practice').onclick=()=>startPractice(shuffle(items).slice(0,20),false,id);$('#learn').onclick=()=>showWords(id)}
function showWords(id){const items=cardItems(id);$('#app').innerHTML=`<div class="view trainer"><button class="back" id="back">← Назад</button><section class="question-card"><div class="eyebrow">Словарь карточки ${id}</div><h2>${esc(db.cards[id-1].title)}</h2><div class="expression-list">${items.map(x=>`<div class="expression"><b>${esc(x.expression)}</b><span>${esc(x.translation)}</span></div>`).join('')}</div></section></div>`;$('#back').onclick=()=>openCard(id)}
function distractors(item,pool){const p=['at','in','on','to','for','from','with','of','by','up','out','about'];return shuffle([...new Set([...p,...pool.map(x=>x.answer).filter(Boolean)])].filter(x=>x!==item.answer)).slice(0,2)}
function startPractice(items,review=false,cardId=null){session={items,current:0,correct:0,wrong:[],review,cardId};question()}function startTest(module){const ids=[module*5-4,module*5-3,module*5-2,module*5-1,module*5];startPractice(shuffle(db.expressions.filter(x=>ids.includes(x.cardId))).slice(0,30),false,ids[4])}
function question(){const s=session,x=s.items[s.current],mode=s.current%3,pool=s.items;if(!x)return finish();let body='';if(mode===0){const opts=shuffle([x.translation,...shuffle(pool.filter(y=>y.id!==x.id).map(y=>y.translation)).slice(0,2)]);body=`<h2>${esc(x.expression)}</h2><div class="choices">${opts.map(o=>`<button class="choice" data-answer="${encodeURIComponent(o)}">${esc(o)}</button>`).join('')}</div>`}else if(mode===1){const opts=shuffle([x.answer,...distractors(x,pool)]);body=`<h2>${esc(x.gapSentence)}</h2><div class="choices">${opts.map(o=>`<button class="choice" data-answer="${encodeURIComponent(o)}">${esc(o)}</button>`).join('')}</div>`}else body=`<h2>${esc(x.gapSentence)}</h2><input class="text-answer" id="typed" autocomplete="off" placeholder="Впиши ответ"><div class="hero-actions"><button class="btn" id="check">Проверить</button></div>`;$('#app').innerHTML=`<div class="view trainer"><button class="back" id="quit">← Завершить позже</button><section class="question-card"><div class="q-top"><span class="q-type">${['Соотнеси с переводом','Выбери правильный вариант','Заполни пропуск'][mode]}</span><span>${s.current+1} / ${s.items.length}</span></div><div class="progress-line" style="margin-top:14px"><span style="width:${s.current/s.items.length*100}%"></span></div>${body}<div id="feedback"></div></section></div>`;$('#quit').onclick=home;document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(decodeURIComponent(b.dataset.answer),mode===0?x.translation:x.answer));if($('#check')){$('#check').onclick=()=>answer($('#typed').value,x.answer);$('#typed').onkeydown=e=>{if(e.key==='Enter')$('#check').click()};$('#typed').focus()}}
async function answer(given,correct){const x=session.items[session.current],ok=given.trim().toLowerCase()===String(correct).trim().toLowerCase();if(ok)session.correct++;else{session.wrong.push(x);if(!state.errors.includes(x.id))state.errors.push(x.id)}if(ok)state.errors=state.errors.filter(id=>id!==x.id);const f=$('#feedback');f.className='feedback';f.innerHTML=ok?`✅ Верно! <b>${esc(x.expression)}</b> — ${esc(x.translation)}`:`💡 Правильный ответ: <b>${esc(correct)}</b><br>${esc(x.expression)} — ${esc(x.translation)}`;document.querySelectorAll('button,input').forEach(e=>e.disabled=true);setTimeout(()=>{session.current++;question()},900)}
async function finish(){const score=Math.round(session.correct/session.items.length*100),passed=score>=80;if(passed&&session.cardId&&!session.review){state.completed[session.cardId]=Math.max(state.completed[session.cardId]||0,score);state.unlocked=Math.max(state.unlocked,Math.min(35,session.cardId+1));state.stars+=score===100?3:score>=90?2:1}await save();$('#app').innerHTML=`<div class="view trainer"><section class="question-card result"><div class="eyebrow">${passed?'Задание выполнено':'Нужно ещё немного практики'}</div><div class="result-score">${score}%</div><h2>${passed?'Отличная работа!':'Разберём ошибки'}</h2><p class="lead" style="margin:auto">Правильных ответов: ${session.correct} из ${session.items.length}.</p><div class="hero-actions" style="justify-content:center">${!passed&&session.wrong.length?'<button class="btn" id="review">Повторить ошибки</button>':''}<button class="btn secondary" id="home">К карте курса</button></div></section></div>`;$('#home').onclick=home;if($('#review'))$('#review').onclick=()=>startPractice(shuffle(session.wrong).slice(0,10),true,session.cardId)}
async function teacherDashboard(){setTop('Преподаватель','T');const snap=await getDocs(collection(firestore,'students')),students=snap.docs.map(d=>({uid:d.id,...d.data()}));$('#app').innerHTML=`<div class="view"><div class="section-head"><div><div class="eyebrow">КАБИНЕТ ПРЕПОДАВАТЕЛЯ</div><h2>Ученики</h2><p>${students.length} профилей</p></div><button class="btn" id="addStudent">+ Создать ученика</button></div><section class="panel teacher-panel"><div class="student-table"><div class="student-row table-head"><span>Ученик</span><span>Прогресс</span><span>Карточка</span><span>Ошибки</span><span></span></div>${students.map(s=>`<div class="student-row"><b>${esc(s.displayName)}</b><span>${Math.round(Object.keys(s.completed||{}).length/35*100)}%</span><span>${s.unlocked||1} / 35</span><span>${(s.errors||[]).length}</span><button class="small-btn" data-delete="${s.uid}">Удалить</button></div>`).join('')||'<p class="empty">Пока нет учеников.</p>'}</div></section></div>`;$('#addStudent').onclick=createStudentDialog;document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeStudent(b.dataset.delete))}
function createStudentDialog(){$('#app').innerHTML=`<div class="view trainer"><button class="back" id="back">← К ученикам</button><section class="question-card"><div class="eyebrow">НОВЫЙ УЧЕНИК</div><h2>Создать профиль</h2><form id="createStudent" class="auth-form"><label>Имя<input id="newName" required placeholder="Например, Марта"></label><label>Личный код<input id="newCode" required minlength="6" maxlength="12" value="${code()}"></label><button class="btn" type="submit">Создать ученика</button></form><p id="createError" class="auth-error"></p></section></div>`;$('#back').onclick=teacherDashboard;$('#createStudent').onsubmit=createStudent}
async function createStudent(e){e.preventDefault();const name=$('#newName').value.trim(),access=$('#newCode').value.trim().toUpperCase();let secondary;try{secondary=initializeApp(firebaseConfig,'student-'+Date.now());const credential=await createUserWithEmailAndPassword(getAuth(secondary),studentEmail(name,access),access);await setDoc(doc(firestore,'students',credential.user.uid),{displayName:name,unlocked:1,completed:{},stars:0,streak:1,errors:[],createdAt:serverTimestamp(),lastActiveAt:serverTimestamp()});await signOut(getAuth(secondary));await deleteApp(secondary);$('#app').innerHTML=`<div class="view trainer"><section class="question-card result"><div class="eyebrow">УЧЕНИК СОЗДАН</div><h2>${esc(name)}</h2><div class="result-score" style="font-size:50px">${esc(access)}</div><p class="lead" style="margin:auto">Скопируйте и передайте этот код ученику.</p><div class="hero-actions" style="justify-content:center"><button class="btn" id="copyCode">Скопировать код</button><button class="btn secondary" id="done">Готово</button></div></section></div>`;$('#copyCode').onclick=()=>navigator.clipboard.writeText(access).then(()=>toast('Код скопирован'));$('#done').onclick=teacherDashboard}catch(err){if(secondary)try{await deleteApp(secondary)}catch{}$('#createError').textContent=err.code==='auth/email-already-in-use'?'Ученик с таким именем и кодом уже существует.':'Не удалось создать ученика. Проверьте настройки Authentication и Firestore.'}}
async function removeStudent(uid){if(!confirm('Удалить профиль и прогресс ученика?'))return;await deleteDoc(doc(firestore,'students',uid));toast('Профиль удалён из базы прогресса');teacherDashboard()}
async function routeUser(u){currentUser=u;if(!u){currentRole=null;authScreen();return}try{const[role,data]=await detectRole(u);currentRole=role;if(role==='teacher'){teacherDashboard();return}if(role==='student'){state={...EMPTY,...data,name:data.displayName};setTop(state.name,state.name.slice(0,2).toUpperCase());home();return}await signOut(auth);authScreen();$('#authError').textContent='Профиль не найден в базе.'}catch{authScreen();$('#authError').textContent='Не удалось загрузить профиль. Проверьте правила Firestore.'}}
async function init(){try{db=await fetch('data/expressions.json').then(r=>r.json());onAuthStateChanged(auth,routeUser)}catch{$('#app').innerHTML='<section class="panel" style="padding:30px"><h1>Не удалось загрузить сайт</h1><p>Откройте его через GitHub Pages.</p></section>'}}
$('#soundBtn').onclick=()=>toast('Звуки включены');$('#profileBtn').onclick=()=>currentUser?logout():toast('Сначала войдите');init();
