export const checkpointSets={
1:[
['We have lived in this neighbourhood ___ ages.','for'],
['People used simple tools ___ ancient times.','in'],
['The museum offers family tickets ___ a low cost.','at'],
['We usually talk about our plans ___ breakfast.','at'],
['The baby finally fell asleep ___ midnight.','at'],
['It is dangerous to walk alone here ___ night.','at'],
['Everyone went silent ___ that moment.','at'],
['Please pay attention ___ the final instruction.','to'],
['___ average, teenagers spend several hours online every day.','on'],
['I was so tired that I went ___ bed early.','to'],
['The cat is hiding ___ the bed.','under'],
['My friends surprised me ___ my birthday.','on'],
['I usually have cereal and fruit ___ breakfast.','for'],
['The streets are quieter ___ night than during the day.','by'],
['Please clean ___ your room before the guests arrive.','up'],
['Her confidence grew day ___ day.','by'],
['I prefer staying at home ___ my day off.','on'],
['We discussed the problem ___ dinner.','at'],
['They cooked pasta ___ dinner.','for'],
['The teacher discouraged us ___ copying answers.','from'],
['She performed on stage ___ the first time.','for'],
['I listen to podcasts ___ my free time.','in'],
['He has loved music ___ an early age.','from'],
['We worked ___ morning till night to finish the project.','from'],
['My brother sometimes plays the guitar just ___ fun.','for']],
2:[
['Marta has a natural ability ___ languages.','in'],
['This course is aimed ___ students preparing for the exam.','at'],
['I found several useful articles ___ climate change.','on'],
['Daniel is especially good ___ grammar.','at'],
['Every learner is capable ___ making progress.','of'],
['We all live ___ planet Earth.','on'],
['She always gets excellent marks ___ English.','in'],
['I inherited my musical talent ___ my grandmother.','from'],
['You should get ready ___ tomorrow’s test.','for'],
['It takes me twenty minutes to get ___ school.','to'],
['The teacher gave a clear explanation ___ the rule.','for'],
['Our class has an important exam ___ English next week.','in'],
['Today we are going to learn ___ British traditions.','about'],
['We had to learn the poem ___ heart.','by'],
['Children learn a great deal ___ their mistakes.','from'],
['Can you make a prediction ___ the ending of the story?','about'],
['I made an appointment ___ my English teacher.','with'],
['This explanation does not make sense ___ me.','to'],
['Try to make use ___ every opportunity to practise.','of'],
['My aunt has been married ___ her husband for twenty years.','to'],
['This scarf does not match ___ your jacket.','with'],
['Your support means a lot ___ me.','to'],
['The two small groups merged ___ one large class.','into'],
['Bear ___ mind that spelling is also important.','in'],
['Do not miss out ___ the chance to join the competition.','on']],
3:[
['Many students are afraid ___ making mistakes in public.','of'],
['After a long discussion, we came ___ an agreement.','to'],
['The committee finally agreed ___ a date for the event.','on'],
['I completely agree ___ your opinion.','with'],
['She was angry ___ her brother for taking her phone.','with'],
['Nobody knew the answer ___ the final question.','to'],
['The friends argued ___ which film to watch.','over'],
['I do not want to argue ___ you about this again.','with'],
['He felt ashamed ___ his rude behaviour.','of'],
['The tourist asked ___ the history of the castle.','about'],
['I asked the librarian ___ some help.','for'],
['You must believe ___ yourself before an important exam.','in'],
['We spoke to our relatives ___ phone.','by'],
['Children ___ three can enter the museum free of charge.','under'],
['Mia fell in love ___ the city during her first visit.','with'],
['Our new neighbour is always friendly ___ everyone.','to'],
['___ my point of view, the second option is better.','from'],
['Teenagers should show respect ___ other people’s opinions.','to'],
['I am going out ___ my friends this evening.','with'],
['My parents were happy ___ my exam result.','about'],
['Are you happy ___ the service you received?','with'],
['___ my opinion, regular practice is the key to success.','in'],
['___ reply to your message, I am sending the requested file.','in'],
['___ terms of price, the two phones are quite similar.','in'],
['The mountains can be seen ___ the background of the photo.','in']],
4:[
['We are meeting at three o’clock ___ the afternoon.','in'],
['Please arrive ___ the airport two hours before departure.','at'],
['Our flight arrived ___ Warsaw just before midnight.','in'],
['She started learning English ___ the age of six.','at'],
['A small café stands ___ the base of the hill.','at'],
['There is a short introduction ___ the beginning of the book.','at'],
['You can buy this medicine ___ the chemist’s.','at'],
['We took dozens of photos ___ the zoo.','at'],
['The climbers reached the summit ___ the cost of great effort.','at'],
['Turn left ___ the crossroads near the library.','at'],
['The answers are printed ___ the end of the book.','at'],
['The children were singing and dancing ___ the same time.','at'],
['We spent the whole summer ___ the seaside.','at'],
['A small flag was flying ___ the top of the tower.','at'],
['What are you planning to do ___ the weekend?','at'],
['We travelled to the city centre ___ bus.','by'],
['Hurry up and get ___ the bus before it leaves.','on'],
['I am busy ___ my homework at the moment.','with'],
['The island can only be reached ___ sea.','by'],
['Good friends genuinely care ___ each other.','about'],
['Could you take care ___ my plants while I am away?','of'],
['The scientists carried ___ several important experiments.','out'],
['___ the contrary, the second task was quite easy.','on'],
['There is a clear difference ___ a habit and a routine.','between'],
['In Britain, people drive ___ the left.','on']],
5:[
['The injured cyclist was admitted ___ hospital immediately.','to'],
['Regular exercise can reduce the risk ___ heart disease.','of'],
['The children are waiting for us ___ the swimming pool.','at'],
['The newspaper reported an attack ___ the city centre.','on'],
['Do not blame others ___ your own mistakes.','for'],
['Olivia is brilliant ___ solving difficult puzzles.','at'],
['She learned to cope ___ stress before exams.','with'],
['Plastic waste is a serious danger ___ marine animals.','to'],
['We were faced ___ an unexpected problem.','with'],
['Most young birds feed ___ insects.','on'],
['I feel sorry ___ anyone who has to work outside today.','for'],
['People have fought ___ equal rights for generations.','for'],
['Can you figure ___ how this machine works?','out'],
['The room was filled ___ the smell of fresh coffee.','with'],
['Please fill ___ this form before your appointment.','in'],
['We need to find out more ___ the causes of the accident.','about'],
['Drivers may receive a fine ___ parking here.','for'],
['Someone tried to set fire ___ the empty building.','to'],
['___ first, the instructions seemed confusing.','at'],
['First ___ all, make sure that you understand the question.','of'],
['This programme is not suitable ___ young children.','for'],
['It was difficult for the new student to fit ___ with the class.','in'],
['Please focus ___ the task instead of checking your phone.','on'],
['Eva decided to follow ___ her mother’s footsteps and become a doctor.','in'],
['We walked all the way there ___ foot.','on']],
6:[
['You must take the weather ___ account before planning the trip.','into'],
['My parents are both ___ work at the moment.','at'],
['She received an award ___ her work with young people.','for'],
['We had a picnic on the bank ___ the river.','of'],
['Mr Brown is in Berlin ___ business this week.','on'],
['Our manager went ___ a business trip to Germany.','on'],
['I took your umbrella ___ mistake.','by'],
['I know the actor’s face, but not ___ name.','by'],
['___ the way, have you finished the report?','by'],
['You cannot move this heavy table ___ yourself.','by'],
['The final grammar exercise was a piece ___ cake.','of'],
['The long meeting finally came ___ an end.','to'],
['___ any case, we should tell the teacher what happened.','in'],
['Keep this number with you ___ case of an emergency.','in'],
['Loud music can cause harm ___ your hearing.','to'],
['Scientists are investigating the cause ___ the unusual weather.','of'],
['We decorated the classroom in celebration ___ our victory.','of'],
['I met my former teacher completely ___ chance.','by'],
['Entrance to the exhibition is free ___ charge.','of'],
['I often chat ___ my classmates after lessons.','with'],
['Passengers must check ___ at least two hours before the flight.','in'],
['You can choose ___ several different courses.','from'],
['Our family usually gets together ___ Christmas.','at'],
['Please comment ___ the main idea of the article.','on'],
['It is hard to concentrate ___ homework when the television is on.','on']],
7:[
['Every student should have access ___ reliable learning materials.','to'],
['I deleted the important file ___ accident.','by'],
['The singer was accompanied ___ a pianist.','by'],
['According ___ the weather forecast, it may snow tonight.','to'],
['The police accused the man ___ stealing the painting.','of'],
['I got acquainted ___ several students on the first day.','with'],
['The students acted ___ the dialogue in pairs.','out'],
['Regular reading adds greatly ___ your vocabulary.','to'],
['Many teenagers struggle with addiction ___ social media.','to'],
['___ addition to English, she speaks Polish and German.','in'],
['The letter was addressed ___ the head teacher.','to'],
['I admire my grandmother ___ her courage and patience.','for'],
['The country has made remarkable advances ___ technology.','in'],
['Could you give me some advice ___ preparing for the exam?','on'],
['Our team finished two points ahead ___ its nearest rival.','of'],
['We were all ___ agreement about the final decision.','in'],
['My brother is allergic ___ nuts.','to'],
['Drinking water is needed ___ large amounts during hot weather.','in'],
['Apart ___ one small error, your essay was excellent.','from'],
['You should apologise ___ being late.','for'],
['The company apologised ___ its customers.','to'],
['This charity appeal is directed ___ young people.','at'],
['More than two hundred students applied ___ the programme.','for'],
['The committee approved ___ the new plan.','of'],
['The two friends walked home arm ___ arm.','in']]
};

const names=['Mia','Emma','Daniel','Sofia','Alex','Olivia'];
export function freshCheckpoint(module){return checkpointSets[module].map((item,index)=>({id:`checkpoint_${module}_${index+1}`,cardId:module*5,answer:item[1],acceptedAnswers:[item[1]],expression:item[0].replace('___',item[1]),translation:'',gapSentence:item[0].replace(/Marta|Daniel|Mia|Eva|Olivia/g,()=>names[Math.floor(Math.random()*names.length)])}));}
